### ISSUE TITLE
UC005 - Atualizar Firmware

### ISSUE THREAD

**Issue by henmerlin** [pjefika/acs2#24]

**Comment by FabioClem** [comment]
Pendente backend

**Comment by henmerlin** [comment]
Equipamentos não possuem firmware preferencial definido pelo ACS:
- Perguntar para Equipe de Engenharia (quando?)

**Comment by henmerlin** [comment]
DeviceGUID: 74021
OUI: 8C10D4
SubscriberID: NO_SUBSCRIBER
ProductClass: F@ST5650
ProductClass: null
Protocol: DEVICE_PROTOCOL_DSLFTR069v1
SerialNumber: N71327865001810
LastContactTime: 2017-03-23T16:49:41.612-03:00
getConnectionRequestURL: http://191.250.106.173:7547/
ConnectionRequestUsername: hdmCRuser
tConnectionRequestPassword: hdmCRpass
Type: 0
Model: Device:1
UserTagArray: LAST_CHK_PSSBA_Start| Valor: 2016/12/03 09:17:22
ServiceTagArray: new_device| Valor: false
ServiceTagArray: notifyIT| Valor: true

firmwareVersion: 8.126.1.28_GVT_BRCM_OMCI
preferredVersion: 8.126.1.28_GVT_BRCM_OMCI-preferred

**Comment by henmerlin** [comment]
Equipamentos só receberão **updateFirmware**  apos a release 2 do acs.
