### ISSUE TITLE
UC011 - Configurar Wi-Fi (Incompleto)

### ISSUE THREAD

**Issue by henmerlin** [pjefika/acs2#31]

**Comment by henmerlin** [comment]
**Pendente:** Utilizar enumerado para Encriptação.

**Comment by henmerlin** [comment]
Criar select com de 1-11 para seleção do canel wifi.

**Comment by Agibert** [comment]
Parâmetro citado na doc como broadcastEnable dispara exceção de parâmetro inválido. Alterado para bcEnable, não dispara exceção porém não efetua alteração.

**Comment by Agibert** [comment]
Parâmetros AuthMode, EncType, Standard não sofrem alteração. Não é possível testar alteração do parâmetro Password

**Comment by henmerlin** [comment]
*Device:* 90022.
*Não realizada sets: SSID, Channel e password.*

**Comment by henmerlin** [comment]
Homologado com device: 89013 - DEVICE_PROTOCOL_DSLFTR069v1
