### ISSUE TITLE
UC016 - Consultar xDSL Diagnostics

### ISSUE THREAD

**Issue by henmerlin** [pjefika/acs2#36]

**Comment by henmerlin** [comment]
mar 13, 2017 4:46:42 PM tests.junit.consulta.XdslDiagnosticJUnitTest xDSLDiagnostic
GRAVE: null
com.motive.synchdeviceopsimpl.synchdeviceoperationsnbiservice.DeviceOperationException: status=1, operationId=168008, faultKey=cwmp.fault.8815, faultString=RUNTIME-ERROR: xDSLDiagnostics:null:52:0:com.alcatel.hdm.javascript.EcmaError: TypeError: Cannot call method "size" of undefined (xDSLDiagnostics#52), faultMsgParams=[tr098_xDSLDiagnostics.js:xDSLDiagnostics, RUNTIME-ERROR: xDSLDiagnostics:null:52:0:com.alcatel.hdm.javascript.EcmaError: TypeError: Cannot call method "size" of undefined (xDSLDiagnostics#52)]

**Comment by henmerlin** [comment]
mar 16, 2017 9:25:30 AM tests.junit.consulta.equipamento.XdslDiagnosticJUnitTest xDSLDiagnostic
GRAVE: null
com.motive.synchdeviceopsimpl.synchdeviceoperationsnbiservice.DeviceOperationException: status=1, operationId=170910, faultKey=cwmp.fault.8815, faultString=RUNTIME-ERROR: xDSLDiagnostics:null:52:0:com.alcatel.hdm.javascript.EcmaError: TypeError: Cannot call method "size" of undefined (xDSLDiagnostics#52), faultMsgParams=[tr098_xDSLDiagnostics.js:xDSLDiagnostics, RUNTIME-ERROR: xDSLDiagnostics:null:52:0:com.alcatel.hdm.javascript.EcmaError: TypeError: Cannot call method "size" of undefined (xDSLDiagnostics#52)]

**Comment by Agibert** [comment]
Quanto aos parâmetros referentes à tabela de CRC:
existem parâmetros que iniciam com ATUC, deixando claro q tratam-se de parâmetros de Downstream porém os demais parâmetros não estão marcados como ATUR(Upstream).
