### ISSUE TITLE
Histórico de Autenticação (Modem)

### ISSUE THREAD

**Issue by Agibert** [pjefika/acs2#82]
Disponibilizar consulta do histórico de autenticação de equipamentos Modem

**Comment by henmerlin** [comment]
Investigar: nbi.getDeviceOperationsHistory();

**Comment by FabioClem** [comment]
Retorno da lista no TDD

getFaultKey: cwmp.fault.8815
    faultMsgParams: tr098_traceroute.js:traceroute
    faultMsgParams: RUNTIME-ERROR: traceroute:null:18:0:com.alcatel.hdm.javascript.WrappedException: Wrapped java.lang.IllegalStateException: Not a JSON Object: null (traceroute#18)
getFaultString: RUNTIME-ERROR: traceroute:null:18:0:com.alcatel.hdm.javascript.WrappedException: Wrapped java.lang.IllegalStateException: Not a JSON Object: null (traceroute#18)
getOperationID: 179964
getStatus: 1
getSubStatus: null
-------------------------------------------------------------------
getFaultKey: cwmp.fault.8815
    faultMsgParams: tr098_traceroute.js:traceroute
    faultMsgParams: RUNTIME-ERROR: traceroute:null:18:0:com.alcatel.hdm.javascript.WrappedException: Wrapped java.lang.IllegalStateException: Not a JSON Object: null (traceroute#18)
getFaultString: RUNTIME-ERROR: traceroute:null:18:0:com.alcatel.hdm.javascript.WrappedException: Wrapped java.lang.IllegalStateException: Not a JSON Object: null (traceroute#18)
getOperationID: 179963
getStatus: 1
getSubStatus: null
-------------------------------------------------------------------
getFaultKey: cwmp.fault.0
getFaultString: null
getOperationID: 179961
getStatus: 0
getSubStatus: null

**Comment by FabioClem** [comment]
retorno TDD
getFaultKey: cwmp.fault.8815
    faultMsgParams: tr098_traceroute.js:traceroute
    faultMsgParams: RUNTIME-ERROR: traceroute:null:18:0:com.alcatel.hdm.javascript.WrappedException: Wrapped java.lang.IllegalStateException: Not a JSON Object: null (traceroute#18)
getFaultString: RUNTIME-ERROR: traceroute:null:18:0:com.alcatel.hdm.javascript.WrappedException: Wrapped java.lang.IllegalStateException: Not a JSON Object: null (traceroute#18)
getOperationID: 179964
getStatus: 1
getSubStatus: nul
